name: Verify and Publish Frontend

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  # Verify the frontend code
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Change directory to frontend
        run: cd frontend

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Test there is no error
        run: npm run lint
        working-directory: frontend
